# Structure of the Guidebook and FAQs 

## What do we need for lab sessions? Who? What?

For our labs we are going to use online resources such as Google Docs and Sheets as well as software such as *MATLAB*.  We will also use *atom*, a basic text editor that's widely used in programming to view and edit files.


## Why are we using these programs?

While most of our stuff will be executed online, getting to know how to use these software tools will allow you to build skill that will be applicable in any profession.

We will use `MATLAB` to build our electronic notebooks, analyze and visualize data. `MATLAB` will also give us the opportunity to learn some programming skills and get introduced to powerful methods for understanding biological systems.

`Atom` will help us read files we wouldn't be able to read otherwise. As we go forward with class we will see some examples of these files.

## Do we need to know how to program?

No. We will learn how to do some basic programming and how to use the command line (i.e. how to use basic commands, how to create folders, execute programs and create loops).

*Being resourceful and using every tool we can is very important. Sometimes things won't work as expected and we MUST find an alternative. This is one of those cases*.

***
