---
title: "Lab 5: Homology and Phylogenetics (Section 2)"
output: html_document
author: "Tamanna Gurung and Johnny Davila Sandoval"
df_print: paged
editor_options:
  chunk_output_type: inline
---

<h2>
<span style="color: red;"> 40/50. Y'all: When using code use code blocks! When using scientific names, use italics!!</span>
</h2>

# Instructions:

- Section 2 will be done on Nov. 13
- Lab is due before Nov. 20

## Creating a phylogenetic tree using protein data

One of the most common ways of creating phylogenetic trees is using protein data, as the length of the protein alignment is usually smaller than the nucleotide alignment. 

### Introduction to `IQ-tree`

In this lab, we will use one of the most recent programs to build phylogenetic trees: [`IQ-tree`](http://www.iqtree.org/).

`IQ-tree` uses a maximum likelihood approach and ultra-fast bootstrapping to reconstruct phylogenetic trees. 

`IQ-tree` is a very fast program, and it can use nucleotide, protein and other types of data to reconstruct phylogenies based on maximum likelihood.

In addition, if you remember from the theory lecture, `IQ-tree` also determines the best model for nucleotide/amino-acid substitution for the phylogenetic reconstruction, so pretty much `IQ-tree` can do it all.

## Running IQ-tree on protein data

So, we are going to use the protein alignment that we created last week.

To run IQ-tree, we need two super-simple commands:

1. Load the module for IQ-tree

```
module load iqtree
```

2. Use this magical command to run `IQ-tree` and automatically determine the best model of amino-acid evolution, run 1000 ultra-fast bootstraps and obtain the most likely tree.

```
iqtree2 -s your_protein_alignment -B 1000
```

3. Answer the following questions:

***
> 1. Check the output of the program as it runs. According to the output, what is the Best-fit model for our alignment?

The best models are LG+I+G4.



> 2. What are the best models according to Akaike information criteria, corrected Akaike information criteria, and Bayesian information criteria? Are they all different?

best_model_AIC: LG+F+I+G4
best_model_AICc: LG+F+I+G4
best_model_BIC: LG+I+G4
Yes, they are different. The model proposed by BIC does not include the parameter F (empirical base frequencies).


> 3. Use code to extract the Log-likelihood of the tree from the `.iqtree` file from the run. What is that value? How did you extracted it? 

The value is -19731.4890 (s.e. 367.1591). We extracted it by using the grep command and looked for the word "likelihood" in the iqtree file.



***

4. To view your final phylogenetic tree, download [FigTree](https://github.com/rambaut/figtree/releases) where the `dmg` is for MacOS, the `zip` for Windows, and the `tgz` for Linux. Install the program.

5. Download the `.treefile` file from the cluster to your computer. Open `FigTree` and open the downloaded `.treefile`.

6. You'll see a window like this. It asks you about what name you want to give the labels of the trees. I usually call them *bootstrap*:


7. Here's your tree! Now, all Maximum Likelihood trees are unrooted by definition. However, its easier to study the tree if you root it. In this case, you can root it on the node with the longest branch. To do so do `Trees -> Root tree -> Midpoint`.

8. You can also organize the tree for easy viewing by organizing it by early-emerging to late emerging. Use `Trees -> Order nodes -> Increasing` to do so.

9. Finally, observe the bootstrap values by selecting `Node Labels -> Bootstrap`. Good boostrap support values are greater than 60%, highly supported values are greater than 75%. 

10. Answer the following question:

***
> 4. Summarize your findings (i.e.: Describe the relationships between the species; which nodes are well supported, which nodes are not; does this tree fit the expectation based on the taxonomy of the species used?)

There is a highly supported node that separates chordates and insects. Within chordates, fishes, amphibians, birds, and mammals are in highly supported nodes. Within mammals, the separation of rodents and the rest of the group is well supported. The separation of fungi and plants is highly supported. Although *Pyricularia*, *Neurospora*, and *Schizosaccharomyces* are from the phylum Ascomycota, the last one is more distantly related than the first two but that relationship is not well supported. Overall, the relationship among these species is the expected based on taxonomy. 


***

## Running IQ-tree on nucelotide data

Now, lets do the same but using the `homologene_nucl.fasta` file you'll find in the moodle page. 

This file has **been previously aligned** using `MAFFT`, so this **SHOULD BE** the same file you got from the `mRNA` homologene file, and we will test this hypothesis. 

11. Align **YOUR** mRNA homologene file you obtained last week using `MAFFT`. Answer the following question.

***

> 5. Add the code for the MAFFT alignment of your mRNA file. 

mafft --genafpair --maxiterate 1000 homologene_nucl.fasta > alin.fasta

<span style="color: red;"> CODE NOTATION!! (-5 pts) </span>.


> 6. Why did you decide to use that algorithm?

We decided to use E-INS because MSH2 is a protein with multiple conserved domains across different species.


***

12. Run `IQ-tree` for each of the mRNA alignments. Fill the following table

| mRNA file | Best nucleotide model | Likelihood score of tree |
|---------|--------|--------|
| Your mRNA file | TIM3+F+I+G4 | -46835.7460 | 
| Professor's mRNA file | TIM3+F+R3 | -49890.4734 |   

13. Open both trees in FigTree. Answer the following question:

***
> 7. What is the most striking difference you see?

*Arabidopsis thaliana* and *Mus musculus*. In our tree, *Arabidopsis* sequence is located at the root of the tree. Instead in professor's file, it is *Mus musculus* that is in that location. 

***

14. Open the professor's alignment in the [MSA viewer of NCBI](https://www.ncbi.nlm.nih.gov/projects/msaviewer/). After uploading the sequence, use the `Coloring -> Nucleic Acid Colors` option. Answer the following question:

***
> 8. There is one sequence that looks very weird (i.e. Colors don't match and there are long strands of insertions and deletions in the region). What sequence do you suspect its weird?

*Mus musculus* is the sequence that looks different to the other ones. 

***

15. The professor just noticed that he changed the sequence of *Mus musculus* (`gi|118130707|ref|NM_008628.2|`) and added the reverse strand instead of the forward strand... WHOOPS.

In this case, `MAFFT` can check all the sequences and correct the direction of the strand. Use the `--adjustdirectionaccurately` option of `MAFFT` to run it. 

So, if you used the `E-INS-i` algorithm, the syntax would be like this:

`mafft --adjustdirectionaccurately --genafpair --maxiterate 1000 homologene_nucl.fasta > professor_corrected.fasta`

Using this info, here's the homework:

## Homework: 

> Using the mis-alignment I sent, correct it using the `MAFFT` code above and run the tree again. Does the tree look like the mRNA you obtained? Write a paragraph about the comparison.


Yes, the tree looks like the mRNA we obtained. Overall, both alignments produce similar trees having the same branches and nodes with minimal variations in bootstraps for both. These nodes with variations are Homo sapiens - (Canis - Bos)
Canis - Bos taurus
Kluyveromyces - Eremothecium

<span style="color: red;"> SCIENTIFIC NOTATION!! (-5 pts) </span>.



